### ISSUE TITLE
[BUG] create-remax-app 在低版本node运行报错

### ISSUE THREAD

**Issue by phshy0607** [remaxjs/remax#1007]
**bug 描述**
低版本8.17.0的nodejs，运行create-remax-app报错，提示`SyntaxError: Unexpected token {`

**复现步骤**
使用node版本 8.17.0，运行npx create-remax-app my-app

**期望结果**
安装成功
或提示node版本过低。
目前给的文案让人摸不着头脑，官方网站快速上手也没有建议node版本。

**版本信息:**

- node版本：8.17.0

**其他信息**
`
/Users/hao/.npm/_npx/8107/lib/node_modules/create-remax-app/node_modules/_fs-extra@9.0.0@fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hao/.npm/_npx/8107/lib/node_modules/create-remax-app/node_modules/_fs-extra@9.0.0@fs-extra/lib/mkdirs/index.js:3:44)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
执行失败：/Users/hao/.npm/_npx/8107/bin/create-remax-app 执行失败：/Users/hao/.npm/_npx/8107/bin/create-remax-app my-app
`

**Comment by yesmeck** [comment]
建议升级 node。

**Comment by yesmeck** [comment]
@phshy0607 帮我们文档上说明下么，目前支持 node 12 以上版本。
