### ISSUE TITLE
[BUG]使用parsec-hooks包报错

### ISSUE THREAD

**Issue by mushan0x0** [remaxjs/remax#1088]
**bug 描述**
使用了parsec-hooks包报错
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
```

**复现步骤**
```
yarn add parsec-hooks
```
```
import { useRefState } from 'parsec-hooks';

export default () => {
  const [] = useRefState(0)
}
```

**期望结果**
不报错

- remax 版本: 2.5.0

**其他信息**
```
internal/validators.js:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at validateString (internal/validators.js:120:11)
    at Object.dirname (path.js:1128:5)
    at /Users/mushan/Documents/project/create-parsec-app-weapp/node_modules/@remax/cli/lib/build/webpack/plugins/OptimizeEntries.js:39:87
    at Array.forEach (<anonymous>)
    at /Users/mushan/Documents/project/create-parsec-app-weapp/node_modules/@remax/cli/lib/build/webpack/plugins/OptimizeEntries.js:37:33
    at Array.forEach (<anonymous>)
    at /Users/mushan/Documents/project/create-parsec-app-weapp/node_modules/@remax/cli/lib/build/webpack/plugins/OptimizeEntries.js:32:36
    at Array.forEach (<anonymous>)
    at OptimizeEntriesPlugin.requireChunks (/Users/mushan/Documents/project/create-parsec-app-weapp/node_modules/@remax/cli/lib/build/webpack/plugins/OptimizeEntries.js:31:33)
    at /Users/mushan/Documents/project/create-parsec-app-weapp/node_modules/@remax/cli/lib/build/webpack/plugins/OptimizeEntries.js:24:22 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by yesmeck** [comment]
![20200616133325](https://user-images.githubusercontent.com/465125/84735395-fe71ff00-afd5-11ea-978a-9555a5fa58e1.jpg)

你们这个包里有个动态  import，小程序不支持的。
