### ISSUE TITLE
可以 使用 dva 嘛？

### ISSUE THREAD

**Issue by newset** [remaxjs/remax#122]
**bug 描述**
 启动时会报错

**复现步骤**

**期望结果**

**复现代码**
```
import dva from 'dva';

// 创建应用
const app = dva();
app.start();
```

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [mac OS]

**其他信息**
```
WAService.js:1 Uncaught Error: module "npm/prop-types/npm/react-is/index.js" is not defined
    at require (WAService.js:1)
    at WAService.js:1
    at index.js:6
    at require (WAService.js:1)
    at WAService.js:1
    at Provider.js:5
    at require (WAService.js:1)
    at WAService.js:1
    at index.js:16
    at require (WAService.js:1)
```

**Comment by Darmody** [comment]
<img width="492" alt="屏幕快照 2019-08-20 15 24 03" src="https://user-images.githubusercontent.com/6788752/63326380-b145e200-c35e-11e9-9baf-41dec160d3e8.png">


dva 本身依赖了 react-dom，从这个层面来讲是不支持的

**Comment by newset** [comment]
> <img alt="屏幕快照 2019-08-20 15 24 03" width="492" src="https://user-images.githubusercontent.com/6788752/63326380-b145e200-c35e-11e9-9baf-41dec160d3e8.png">
> 
> dva 本身依赖了 react-dom，从这个层面来讲是不支持的

哦哦， 这个给忘了。
刚看了下只有直接使用 dva-core，我先尝试下

**Comment by yesmeck** [comment]
dva-core 应该是需要简单适配一下的

**Comment by Darmody** [comment]
@newset 成功了吗

**Comment by newset** [comment]
> @newset 成功了吗

没呢，有其他事情在搞。有结果了，我贴出来。可以加到文档里面

**Comment by Darmody** [comment]
> > @newset 成功了吗
> 
> 没呢，有其他事情在搞。有结果了，我贴出来。可以加到文档里面

💯 respect

**Comment by xiaohuoni** [comment]
试了一下，不太行。
可能需要累类似remax-redux-helpers的东西
@yesmeck 
```
yarn add react-redux dva-core
yarn dev
$ remax build -t wechat -w
🚀 启动 watch
🚚 编译...
(17): node_modules/remax/lib/hooks.js
🚨 [UNRESOLVED_IMPORT]: Could not resolve '../utils' from src/models/app.js
(node:71564) UnhandledPromiseRejectionWarning: Error: Could not resolve '../utils' from src/models/app.js
    at error (/Users/xiaohuoni/my-app/node_modules/rollup/dist/rollup.js:9429:30)
    at ModuleLoader.handleMissingImports (/Users/xiaohuoni/my-app/node_modules/rollup/dist/rollup.js:16469:17)
    at ModuleLoader.<anonymous> (/Users/xiaohuoni/my-app/node_modules/rollup/dist/rollup.js:16520:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xiaohuoni/my-app/node_modules/rollup/dist/rollup.js:40:28)
(node:71564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:71564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(186): /Users/xiaohuoni/my-app/node_modules/core-js/library/modules/es6.promise.js?commonjs-proxy'react-dom' is imported by node_modules/react-redux/es/utils/reactBatchedUpdates.js, but could not be resolved – treating it as an external dependency
✨  Done in 12.39s.
```

**Comment by yesmeck** [comment]
对，react-redux 不能直接用，要做一些小改造。

**Comment by yesmeck** [comment]
可以参考 https://github.com/starandtina/tinyapp-redux 对 react-redux 做改造

**Comment by yesmeck** [comment]
因为小程序其实是个多页应用，没有一个总的入口来加 `Provider`，需要改造 `Provider`

**Comment by xiaohuoni** [comment]
依赖getApp做store，不知道可不可行？

**Comment by yesmeck** [comment]
应该可行的，把 store 挂到 App 上。

**Comment by newset** [comment]
@yesmeck 
目前尝试在支持App 为React 实例的版本上直接引入react-redux 来计入。
官方在 react-redux/src/alternate-renderers.js 中提供一个 不用react-dom 的版本 。

我用最新版的1.1.0-alpha 试了下，目前卡在这里了

```
Error: Unexpected token
    at error (/Users/Doctorwork/Sites/source/remax-demo/node_modules/rollup/dist/rollup.js:9419:30)
    at Module.error (/Users/Doctorwork/Sites/source/remax-demo/node_modules/rollup/dist/rollup.js:13402:9)
    at tryParse (/Users/Doctorwork/Sites/source/remax-demo/node_modules/rollup/dist/rollup.js:13315:16)
    at Module.setSource (/Users/Doctorwork/Sites/source/remax-demo/node_modules/rollup/dist/rollup.js:13629:33)
    at /Users/Doctorwork/Sites/source/remax-demo/node_modules/rollup/dist/rollup.js:16423:20 {
  code: 'PARSE_ERROR',
  pos: 14528,
  loc: {
    column: 6,
    file: '/Users/Doctorwork/Sites/source/remax-demo/node_modules/prop-types/factoryWithTypeCheckers.js',
    line: 365
  },
  frame: '363:   function createUnionTypeChecker(arrayOfTypeCheckers) {\n' +
    '364:     if (!Array.isArray(arrayOfTypeCheckers)) {\n' +
    "365:       process.env.NODE_ENV !== 'production' ? printWarning('Invalid argument supplied to oneOfType, expected an instance of array.') : void 0;\n" +
    '           ^\n' +
    '366:       return emptyFunctionThatReturnsNull;\n' +
    '367:     }'
```

**Comment by newset** [comment]
这个是我用来测试的 代码库

https://github.com/newset/remax-demo

**Comment by newset** [comment]
> 因为小程序其实是个多页应用，没有一个总的入口来加 `Provider`，需要改造 `Provider`

现在应该可以在App 中加入 react-redux 的 Provider 了吧

**Comment by yesmeck** [comment]
这个 `node_modules/prop-types/factoryWithTypeCheckers.js` 有语法错误我也碰到了，很奇怪。报错那行删掉就可以了。

**Comment by yesmeck** [comment]
redux https://github.com/remaxjs/todo-demo/tree/redux/alipay

**Comment by newset** [comment]
https://github.com/remaxjs/remax/commit/f98b0ca7beb6d3020f5a2bb7c6463e323dee6ce1

这个 `修复带有 __esModule 标示的 cjs 模块不能正确 import 的问题`

会导致 dva-core 引入后无法正常使用。

**Comment by newset** [comment]
https://github.com/rollup/rollup-plugin-commonjs/issues/408

**Comment by yesmeck** [comment]
dva https://github.com/remaxjs/todo-demo/tree/dva/alipay
