### ISSUE TITLE
[问题] remax.config.js 中的 configWebpack 配置求解

### ISSUE THREAD

**Issue by war408705279** [remaxjs/remax#1253]
先贴一下版本信息
```
"dependencies": {
  "@svgr/webpack": "^5.4.0",
  "remax": "^2.6.0"
  ...
},
"devDependencies": {
  "file-loader": "^6.0.0",
  "svgo-loader": "^2.2.1",
  "typescript": "^3.7.3",
  ...
}
```
操作系统：`macOS`
构建目标小程序：`wechat`
已经自查了文件路径都是对的。`webpack` 的配置信息也是从现有的一个 `web` 项目 `copy` 过来的，怀疑是改成 `webpack-chain` 的时候出了什么问题（导致配置没有生效），找了很多资料都没有解决，所以来请教一下~

有两个问题

- 问题 `1`

**问题描述**
期望可以在 `config.ts` 文件中通过配置的路径（不是相对路径）引入其他文件 `export` 出来的常量

**示例代码**
`remax.config.js` 中增加的配置
```js
// remax.config.js
module.exports = {
  ...
  configWebpack({ config }) {
    config.resolve
      .extensions
        .merge(['.ts', '.tsx', '.js', '.jsx', '.json'])
    config.resolve
      .alias
        .merge({
          'utils': path.resolve(__dirname, 'src/utils'),
          ...
        })
  }
}
```
`config.ts` 中的引入方式

`import { color } from 'utils/styles/variables'`

本地运行时报错

```
Error: Cannot find module 'utils/styles/variables'
Require stack:
- /Users/jiayizhen/qbox/portal-mp/src/utils/config.ts
- /Users/jiayizhen/qbox/portal-mp/src/app.config.ts
- /Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/readManifest.js
- /Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/build/utils/getAppConfig.js
- /Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/getEntries.js
- /Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/build/webpack/config.mini.js
- /Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/build/mini.js
- /Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/index.js
- /Users/jiayizhen/qbox/portal-mp/node_modules/remax/bin/remax
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jiayizhen/qbox/portal-mp/src/utils/config.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (/Users/jiayizhen/qbox/portal-mp/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .ts] (/Users/jiayizhen/qbox/portal-mp/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jiayizhen/qbox/portal-mp/src/app.config.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (/Users/jiayizhen/qbox/portal-mp/node_modules/pirates/lib/index.js:99:24) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jiayizhen/qbox/portal-mp/src/utils/config.ts',
    '/Users/jiayizhen/qbox/portal-mp/src/app.config.ts',
    '/Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/readManifest.js',
    '/Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/build/utils/getAppConfig.js',
    '/Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/getEntries.js',
    '/Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/build/webpack/config.mini.js',
    '/Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/build/mini.js',
    '/Users/jiayizhen/qbox/portal-mp/node_modules/@remax/cli/lib/index.js',
    '/Users/jiayizhen/qbox/portal-mp/node_modules/remax/bin/remax'
  ]
}
```
**其他信息**
报错截图
![image](https://user-images.githubusercontent.com/23465865/91244522-1c4ea380-e77f-11ea-82f3-2629dae574f9.png)

- 问题 `2`

**问题描述**
期望可以将 `*.file.svg` 文件引入为路径地址（`string`），增加了 `file-loader && svgo-loader` 依赖

**示例代码**
`remax.config.js` 中增加的配置
```js
// remax.config.js
module.exports = {
  ...
  config.module
    .rule('js-ts-file-svg')
    .test(/\.file\.svg$/i)
    .issuer({
      test: /\.(js|ts)x?$/
    })
    .use('file-loader')
    .loader(require.resolve('file-loader'))
    .options({
      name: '[name].[hash].[ext]',
      esModule: false
    })
    .end()
    .use('svgo-loader')
    .loader('svgo-loader')
}
```

`*.file.svg` 文件引入方式如下

`import IconIndexSVGURL from '../../public/images/tabBar/icon-index.file.svg'`

本地运行时报错

```
/Users/jiayizhen/qbox/portal-mp/public/images/tabBar/icon-index.file.svg:1
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24">
^

SyntaxError: Unexpected token '<'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jiayizhen/qbox/portal-mp/src/utils/config.ts:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (/Users/jiayizhen/qbox/portal-mp/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .ts] (/Users/jiayizhen/qbox/portal-mp/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**其他信息**
报错截图
![image](https://user-images.githubusercontent.com/23465865/91245490-29b85d80-e780-11ea-9ab4-eaa3aae06512.png)

期待各位大佬的回复~

**Comment by yesmeck** [comment]
@war408705279 提供个重现的仓库吧，我帮你看看

**Comment by war408705279** [comment]
> @war408705279 提供个重现的仓库吧，我帮你看看

写大佬，麻烦看一下这个 `repo` https://github.com/war408705279/vulcan
全局搜 `Remax issues 1253` 就可以，加了注释

**Comment by war408705279** [comment]
@yesmeck 
大佬，`utils/config.ts` 里面 `export` 出来的 `getWechatAppConfig() && getWechatPageConfig()` 是在 `app.config.ts` 文件中用到了，我发现只有在这里使用上面的写法编译才会报错。在其他地方（例如 `pages/index/index.tsx`）里面这么写是不会报错的，不知道这个是不是 `remax` 编译时候的问题

**Comment by war408705279** [comment]
另外我发现在使用 `@svgr/webpack` 把 `svg` 转换为 `React Component` 的时候也有问题
报错信息如下
```
/base.wxml
 Template `REMAX_TPL_1_svg` not found.
  3273 | 
  3274 | <template name="REMAX_TPL_2_CONTAINER" data="{{i: i}}">
> 3275 | 	<template is="{{_h.tid(i.type, a)}}" data="{{i: i, a: a + ',' + i.type, tid: 2}}" />
       | 	             ^
  3276 | </template>
  3277 | 
  3278 | <template name="REMAX_TPL_3_CONTAINER" data="{{i: i}}">
```
我把复现的代码也加到 `repo` 里面了
https://github.com/war408705279/vulcan/blob/master/remax.config.js#L41
https://github.com/war408705279/vulcan/blob/master/src/pages/index/index.tsx#L13

**Comment by yesmeck** [comment]
> 把 svg 转换为 React Component 的时候

这个是不支持的。

**Comment by war408705279** [comment]
> > 把 svg 转换为 React Component 的时候
> 
> 这个是不支持的。

收到，大佬，后面有计划支持么？

**Comment by yesmeck** [comment]
小程序的限制，我们没法支持。

**Comment by war408705279** [comment]
> 小程序的限制，我们没法支持。

好的吧~

**Comment by Darmody** [comment]
![Screen Shot 2020-09-10 at 3 16 52 PM](https://user-images.githubusercontent.com/6788752/92693936-e1509080-f378-11ea-8360-1fb06b907e5b.png)

**Comment by Darmody** [comment]
alias 是这样配置的
