### ISSUE TITLE
[BUG]npm run dev 时报错 Unexpected token 'export'

### ISSUE THREAD

**Issue by thelittlehan** [remaxjs/remax#1267]
**bug 描述**
npm run dev 时报错

**版本信息:**
- remax 版本: 2.7.8
- 小程序端  微信小程序

**其他信息**
/Users/chen/Desktop/code/test/remax-mp/node_modules/node-notifier/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/chen/Desktop/code/test/remax-mp/node_modules/node-notifier/notifiers/toaster.js:9:22)

![image](https://user-images.githubusercontent.com/17919546/92231032-a369ed00-eede-11ea-9ee0-01bd3f597d4a.png)

**Comment by thelittlehan** [comment]
node版本如下
➜  remax-mp node --version
v13.6.0
➜  remax-mp npm --version
6.13.4

**Comment by yesmeck** [comment]
是在配置文件里引用了 ESM 文件吗？
