### ISSUE TITLE
[BUG] 2.13.1 版本执行提示如下错误Cannot read property 'filter' of undefined 还有其他错误，麻烦看一下是否是依赖错误

### ISSUE THREAD

**Issue by fewoy** [remaxjs/remax#1571]
**bug 描述**
本地运行和打包都失败

**复现步骤**
**执行命令1：:**
 "dev:wx": "cross-env remax build -w -t wechat",
**提示错误**
(node:20064) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:20064) UnhandledPromiseRejectionWarning: TypeError: D:\mp\node_modules\@remax\wechat\templates\base.ejs:29
    27| </wxs>
    28| <% for (let component of components) { %><% var len = depth[component.id] || 10; %><% for (var i = 1; i <= len; i++) { %>
 >> 29|                 <%- include('./component.ejs', {
    30|                         props: component.props,
    31|                         id: component.id,
    32|                         templateId: i,

D:\EcCode\Fork\vrn-pages\node_modules\@remax\wechat\templates\component.ejs:27
    25|   </block>
    26| <%_ } else { _%>
 >> 27|   <<%=id%> <%- propsKeyTpl(props, false) %>>
    28|     <%- include('./children.ejs', { props: props, id: id, type: type, slotView: slotView }) %>
    29|   </<%=id%>>
    30| <%_ } _%>

Cannot read property 'filter' of undefined
    at propsKeyTpl (eval at compile (D:\mp\node_modules\ejs\lib\ejs.js:662:12), <anonymous>:19:21)
    at eval (eval at compile (D:\mp\node_modules\ejs\lib\ejs.js:662:12), <anonymous>:60:17)
    at component (D:\mp\node_modules\ejs\lib\ejs.js:692:17)
    at include (D:\mp\node_modules\ejs\lib\ejs.js:690:39)
    at eval (eval at compile (D:\mp\node_modules\ejs\lib\ejs.js:662:12), <anonymous>:15:17)
    at base (D:\mp\node_modules\ejs\lib\ejs.js:692:17)
    at D:\mp\node_modules\ejs\lib\ejs.js:258:40
    at new Promise (<anonymous>)
    at tryHandleCache (D:\mp\node_modules\ejs\lib\ejs.js:256:14)
    at Object.exports.renderFile (D:\mp\node_modules\ejs\lib\ejs.js:489:10)
    at Object.createBaseTemplate (D:\mp\node_modules\@remax\cli\lib\build\webpack\plugins\PageAsset\createTemplate.js:75:38)
    at D:\mp\node_modules\@remax\cli\lib\build\webpack\plugins\PageAsset\index.js:44:36
    at _next1 (eval at create (D:\mp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1)
    at eval (eval at create (D:\mp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:39:1)
    at D:\mp\node_modules\@remax\cli\lib\build\webpack\plugins\AppAsset.js:17:13
(node:20064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:20064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**执行命令2：**

   "build:wx": "cross-env NODE_ENV=production remax build -t wechat -m -a"

提示错误：

� ./mp/pages/home/home.js
Module build failed (from ./node_modules/@remax/cli/lib/build/webpack/loaders/babel.js):
TypeError: D:\mp\pages\home\home.js: Cannot read property 'includes' of undefined
    at registerHostComponentManifest (D:\mp\node_modules\babel-plugin-remax-host-component\lib\index.js:172:44)
    at PluginPass.JSXElement (D:\mp\node_modules\babel-plugin-remax-host-component\lib\index.js:249:25)
    at newFn (D:\mp\node_modules\@babel\traverse\lib\visitors.js:175:21)
    at NodePath._call (D:\mp\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (D:\mp\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (D:\mp\node_modules\@babel\traverse\lib\path\context.js:92:31)
    at TraversalContext.visitQueue (D:\mp\node_modules\@babel\traverse\lib\context.js:116:16)
    at TraversalContext.visitSingle (D:\mp\node_modules\@babel\traverse\lib\context.js:85:19)
    at TraversalContext.visit (D:\mp\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node D:\mp\node_modules\@babel\traverse\lib\index.js:82:17)
    at NodePath.visit (D:\mp\node_modules\@babel\traverse\lib\path\context.js:99:18)
    at TraversalContext.visitQueue (D:\mp\node_modules\@babel\traverse\lib\context.js:116:16)
    at TraversalContext.visitSingle (D:\mp\node_modules\@babel\traverse\lib\context.js:85:19)
    at TraversalContext.visit (D:\mp\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (D:\mp\node_modules\@babel\traverse\lib\index.js:82:17)
    at NodePath.visit (D:\mp\node_modules\@babel\traverse\lib\path\context.js:99:18)
 @ ./mp/pages/home/home.entry.js 1:45-78 1:100-105
 @ multi ./mp/pages/home/home.entry.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vrn-pages@0.0.1 build:wx: `cross-env NODE_ENV=production remax build -t wechat -m -a`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vrn-pages@0.0.1 build:wx script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**期望结果**
正常运行

**复现代码**

**版本信息:**

- remax 版本: [2.13.1]
- 开发环境 [windows]

**其他信息**

**Comment by yesmeck** [comment]
能提供一个可重现的 demo 吗？

**Comment by fewoy** [comment]
这个大概是什么原因知道吗，我这边排查一下？代码不能传上来的

**Comment by fewoy** [comment]
我知道原因了。是我两个库，一个依赖另一个，用的remax版本不一致导致的问题，
